### ISSUE TITLE
Demonstrate inspector.css in the README.

### ISSUE THREAD

**Issue by mbostock** [observablehq/runtime#154]
We should include an example of loading the default [inspector.css](https://cdn.jsdelivr.net/npm/@observablehq/inspector@3/dist/inspector.css) in the README.

**Comment by mbostock** [comment]
And, as Jeremy suggests, maybe an example of how to hide the cell names in inspector output if you don’t want them.

```css
.observablehq--cellname { display: none; }
```
